blank_issues_enabled: true
contact_links:
  - name: ℹ Mithril.js bugs
    url: https://github.com/MithrilJS/mithril.js/issues/new
    about: |
      Found a bug in Mithril.js? File an issue in the Mithril.js core repo. This is strictly for
      documentation.
  - name: ℹ Questions, Ideas, and Discussions
    url: https://github.com/MithrilJS/mithril.js/discussions
    about: |
      Got a question on how to use Mithril.js? Have a fancy idea of how we could do better? Check
      out our discussions forum!
  - name: ℹ Show and Tell
    url: https://github.com/MithrilJS/mithril.js/discussions/new?category=show-and-tell
    about: |
      Got something to show off? Made something so cool, you just have to tell the world? Let us
      know here in our discussions forum!
  - name: 💻 Zulip Chat
    url: https://mithril.zulipchat.com/
    about: Not sure about something? Just want to hang out? Come over to our Zulip chat!
