name: merge

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency: deploy

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - run: git clone --depth=1 "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git" .
    - run: npm ci
    - run: npm run build
    - uses: MithrilJS/infra/deploy@main
      with:
        type: gh-pages
        token: ${{ secrets.DEPLOY_TOKEN }}
        root_dir: ${{ github.workspace }}/dist
