name: Notify triage on issue create
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
permissions:
  issues: write
  repository-projects: write
jobs:
  reject:
    uses: MithrilJS/infra/.github/workflows/notify-triage.yml@main
