name: Notify triage on issue create
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  reject:
    uses: MithrilJS/infra/.github/workflows/notify-triage.yml@main
    secrets: inherit
