name: test

on:
  pull_request_target:
    branches: [main]
  push:
    branches: [main, 'push-action/**']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    uses: MithrilJS/infra/.github/workflows/run-tests.yml@main
