name: test

on:
  pull_request_target:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    uses: MithrilJS/infra/.github/workflows/run-tests.yml@main
    with:
      all-platforms: true
      all-versions: true
