name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

# This uses actions/checkout instead of `git clone` directly since it's way
# easier than parsing everything out.

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
    - run: npm run lint
    - run: npm run build
